### ISSUE TITLE
Feature request: Date range preset buttons

### ISSUE THREAD

**Issue by FloEdelmann** [fxedel/vaterstetten-in-zahlen#12]
Right now, you can select the date via the `dateRangeInput`, which is quite cumbersome though.
E.g. to view *all* Corona cases (which only displays 4 weeks by default), I have to click 13 times on "previous month".

I suggest adding the following buttons to select the date range:

* last 7 days / last week
* last 30 days / last month
* last 90 days / last 3 months
* last 365 days / last year
* all data

The UI could then look like this:

```
Daten anzeigen von [12. Mai 2021 bis 9. Juni 2021] [letzter Woche] [letztem Monat] [letzten 90 Tagen] [letztem Jahr] [gesamten Zeitraum]
☑ Zahlenwerte anzeigen
```

The button "last year" doesn't make sense for vaccinations right now, because the there isn't enough data, so it shouldn't be displayed there.

**Comment by fxedel** [comment]
Already fixed for vaccinations via plotly's range selectors; I need to migrate the corona plots soon.
