### ISSUE TITLE
Map data in Kommunalwahlen 2020 don't load on page load

### ISSUE THREAD

**Issue by FloEdelmann** [fxedel/vaterstetten-in-zahlen#28]
Steps to reproduce:

1. Go to https://vaterstetten-in-zahlen.de/?tab=kommunalwahl2020 (directly or via an in-app link)
2. See this result:
  ![image](https://user-images.githubusercontent.com/202916/155310247-a4a2213e-86e2-46cf-a6d5-253440f33984.png)
3. See these console errors:
  ![image](https://user-images.githubusercontent.com/202916/155310334-970c3e40-ac59-41a1-92d9-580e1711c599.png)

Changing any dropdown loads the map data as expected, also changing it back to the default value works.

**Comment by fxedel** [comment]
Finally had some time to fix this. It seemed to be a kind of timing problem / race condition, since the map is not initialized with render() when the print function tries to find the map by its id and update its layers.
