### ISSUE TITLE
Europawahl 2024

### ISSUE THREAD

**Issue by fxedel** [fxedel/vaterstetten-in-zahlen#55]
Results available here: https://wahlen.osrz-akdb.de/ob-p/175000/0/20240609/europawahl_kreis/ergebnisse_gemeinde_09175132.html

Open data: https://wahlen.osrz-akdb.de/ob-p/175000/0/20240609/europawahl_kreis/presse.html

Raw data: [stimmen.csv](https://github.com/user-attachments/files/16267901/stimmen.csv)

Voting districts need to be asked from Gemeinde Vaterstetten.

Visualization similar to other elections.

**Comment by FloEdelmann** [comment]
For reference:

* https://github.com/fxedel/vaterstetten-in-zahlen/commit/691905445d08ec29e06e4f5ba9e6ec25b399e36e
* https://github.com/fxedel/vaterstetten-in-zahlen/commit/2cb08b415fbf5e5f2a2968cdc36145e5dbeca553
* https://github.com/fxedel/vaterstetten-in-zahlen/commit/30df00169aedf30283701fca12d0575b11bce7ec
* https://github.com/fxedel/vaterstetten-in-zahlen/commit/4a36a030d03d9860be9fcb1e0a6b2bb680de4e23
